name: parsianotp
description: OTP Generator for Parsian Bank

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
#  path_provider: ^1.6.11
  dio: ^4.0.6
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  json_annotation: ^4.7.0
  lottie: ^1.4.3
  another_flushbar: ^1.12.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  hive_generator: ^1.1.3
  json_serializable: ^6.4.0
  retrofit_generator: ^4.0.3+2
  get_it: ^7.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
